chore: optimize build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,57 +5,52 @@ on:
       - build-app-service
 jobs:
   main:
+    name: Build
     runs-on: ubuntu-latest
+    env:
+      NAMESPACE: "myownradio"
+      SERVICE_NAME: ${{ matrix.service_name }}
+      IMAGE_TAG: ${{ github.event.client_payload.tag }}
+      IMAGE_NAME: ${NAMESPACE}/${SERVICE_NAME}
+      IMAGE_URL: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
+      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
     strategy:
       matrix:
         service_name: ${{ github.event.client_payload.services }}
     steps:
       - name: Checkout
         uses: actions/checkout@master
-      - name: Define variables
-        id: variables
-        shell: bash
-        run: |
-          STACK_NAME="myownradio"
-          SERVICE_NAME=$(echo ${{ matrix.service_name }})
-
-          IMAGE_NAME=$(echo ${STACK_NAME}/${SERVICE_NAME})
-          IMAGE_TAG=$(echo ${{ github.event.client_payload.tag }})
-          IMAGE_URL=$(echo ${{ secrets.DOCKER_REGISTRY }}/${IMAGE_NAME}):${IMAGE_TAG}
-
-          echo "##[set-output name=service_name;]$(echo ${SERVICE_NAME})"
-          echo "##[set-output name=image_name;]$(echo ${IMAGE_NAME})"
-          echo "##[set-output name=image_tag;]$(echo ${IMAGE_TAG})"
-          echo "##[set-output name=image_url;]$(echo ${IMAGE_URL})"
-      - name: Preflight Checks
-        shell: bash
-        run: '[ -f "app/services/${{ steps.variables.outputs.service_name }}/Dockerfile" ] || (echo "Dockerfile not found" && exit 1)'
-      - name: Build myownradio/${{ steps.variables.outputs.image_name }}
+      - name: Preflight
+        run: '[ -f "app/services/${SERVICE_NAME}/Dockerfile" ] || (echo "Dockerfile not found" && exit 1)'
+      - name: Build
         uses: docker/build-push-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-          registry: ${{ secrets.DOCKER_REGISTRY }}
-          repository: ${{ steps.variables.outputs.image_name }}
+          registry: ${DOCKER_REGISTRY}
+          repository: ${IMAGE_NAME}
           path: app
-          dockerfile: app/services/${{ steps.variables.outputs.service_name }}/Dockerfile
-          tags: ${{ steps.variables.outputs.image_tag }},latest
+          dockerfile: app/services/${SERVICE_NAME}/Dockerfile
+          tags: ${IMAGE_TAG},latest
   patch:
+    name: Patch
     needs: main
     runs-on: ubuntu-latest
+    env:
+      NAMESPACE: "myownradio"
+      IMAGE_TAG: ${{ github.event.client_payload.tag }}
+      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
+      SERVICES_LIST: ${{ join(github.event.client_payload.services, ' ') }}
     steps:
-      - name: Generate Patch Expression
+      - name: Create Patch
         id: patch_expression
         shell: bash
-        # todo move global variables into special job
         run: |
-          SERVICES_LIST=$(echo ${{ join(github.event.client_payload.services, ' ') }})
-          PATCH_EXPRESSION=$(echo $(for SERVICE in $SERVICES_LIST; do echo services.$SERVICE.image=${{ secrets.DOCKER_REGISTRY }}/myownradio/$SERVICE:${{ github.event.client_payload.tag }}; done))
+          PATCH_EXPRESSION=$(echo
+            $(for SERVICE in ${SERVICES_LIST}; do
+              echo services.${SERVICE}.image=${DOCKER_REGISTRY}/${NAMESPACE}/${SERVICE}:${IMAGE_TAG}; done))
           echo "##[set-output name=patch_expression;]$(echo ${PATCH_EXPRESSION})"
-      - name: Check Patch Expression
-        shell: bash
-        run: echo $(echo ${{ steps.patch_expression.outputs.patch_expression }})
-      - name: Patch stack file through commit
+      - name: Apply Patch
         uses: pldin601/patch-yaml-through-commit@master
         with:
           git_repo_url: https://pldin601:${{ secrets.GIT_PUSH_TOKEN }}@github.com/myownradio/myownradio-env.git
